---
name: run shellcheck and shfmt
on:
  push:
    paths:
      - 'coffin.bash'
      - 'open.bash'
      - 'close.bash'
      - 'timer.bash'
  pull_request:
    paths:
      - 'coffin.bash'
      - 'open.bash'
      - 'close.bash'
      - 'timer.bash'
jobs:
  lint:
    name: use shellcheck to lint pass-coffin
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck-alpine:stable
    steps:
      - name: checkout pass-coffin for shellcheck
        uses: actions/checkout@v3
      - name: run shellcheck
        run: shellcheck coffin.bash open.bash close.bash timer.bash
  format:
    name: use shfmt to check pass-coffin code format
    runs-on: ubuntu-latest
    container:
      image: mvdan/shfmt:v3-alpine
    steps:
      - name: checkout pass-coffin for shfmt
        uses: actions/checkout@v3
      - name: run shfmt
        run: shfmt -d -s -i 2 -bn -ci -sr coffin.bash open.bash close.bash timer.bash
